---
- name: Install essential packages
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name: 
          - tmux
          - stow
          - xclip
          - zsh
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - build-essential
          - fzf
          - lsd
          - terraform
          - python3
          - python3-pip
          - python3-jinja2
        state: present
        update_cache: yes

    - name: Change shell to zsh for all users
      shell: chsh -s /usr/bin/zsh "{{ lookup('ansible.builtin.env', 'USER') }}"
      args:
        executable: /bin/bash

    - name: Install TMUX plugin manager 
      shell: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
      args:
        executable: /bin/bash

    - name: Clone Neovim stable branch
      git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: /usr/local/src/neovim
        version: stable

    - name: Build Neovim
      shell: |
        cd /usr/local/src/neovim
        make CMAKE_BUILD_TYPE=Release
        make install
      args:
        executable: /bin/bash

    - name: Post install
      debug:
        msg: "Run 'curl -sS https://starship.rs/install.sh | sh' to install starship prompt and remember to stow your dotfiles" 
    
