# Options
set -g mouse on
set-option -g allow-rename off
set -g base-index 1
setw -g pane-base-index 1
set -g default-shell /bin/zsh
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g allow-passthrough on
# Binds
# Remap prefix
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix


# Split panes
bind - split-window -v
bind = split-window -h
unbind '"'
unbind %

# Fast reload config
bind r source-file ~/.tmux.conf

# Pane switching
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -n M-H resize-pane -L
bind -n M-L resize-pane -R
bind -n M-K resize-pane -U
bind -n M-J resize-pane -D


unbind Tab
bind Tab select-window -n 
unbind n
bind v new-window -n nvim -c "#{pane_current_path}" nvim
bind-key x kill-pane

unbind l 
bind l swap-pane -d -t '{right-of}'
unbind h
bind h swap-pane -d -t '{left-of}'
bind j swap-pane -d -t '{down-of}'
unbind k
bind k swap-pane -d -t '{up-of}'

# Chose tree order
bind s choose-tree -Zs -O name

# List of plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'vndmp4/tmux-fzf-session-switch'
set -g @plugin 'jimeh/tmux-themepack'



set-option -g @fzf-goto-session-only 'true'
set -g @fzf-goto-session 'o'
set -g @fzf-goto-preview-enabled 'true'
set -g status-position top

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

