---
- name: Setup Fedora Development Environment
  hosts: localhost
  connection: local

  vars_files:
    - vars/packages.yml

  tasks:
    - name: Update all system packages
      become: yes
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      tags:
        - system

    - name: Install development packages
      become: yes
      dnf:
        name: "{{ packages }}"
        state: present
      tags:
        - packages

    - name: Ensure dnf-plugins-core is installed
      become: yes
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
      tags:
        - lazygit


    - name: Enable atim/lazygit Copr repository
      become: yes
      ansible.builtin.command: dnf copr enable -y atim/lazygit
      args:
        creates: /etc/yum.repos.d/_copr_atim-lazygit.repo
      tags:
        - lazygit

    - name: Install lazygit
      become: yes
      ansible.builtin.dnf:
        name: lazygit
        state: present
      tags:
        - lazygit

    - name: Ensure dnf-plugins-core is installed for Yazi COPR
      become: yes
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
      tags:
        - yazi

    - name: Enable lihaohong/yazi Copr repository
      become: yes
      ansible.builtin.command: dnf copr enable -y lihaohong/yazi
      args:
        creates: /etc/yum.repos.d/_copr_lihaohong-yazi.repo
      tags:
        - yazi

    - name: Install Yazi and recommended dependencies
      become: yes
      ansible.builtin.dnf:
        name:
          - yazi
          - p7zip # 7zip
          - jq
          - poppler
          - fd-find # fd
          - ripgrep
          - fzf
          - zoxide
          - ImageMagick
          - xclip # for clipboard support
        state: present
      tags:
        - yazi



    - name: Check if pyenv is installed
      stat:
        path: "{{ ansible_user_dir }}/.pyenv"
      register: pyenv_stat
      become: no

    - name: Install pyenv
      ansible.builtin.git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest: "{{ ansible_user_dir }}/.pyenv"
      when: not pyenv_stat.stat.exists
      become: no
      tags:
        - pyenv

    - name: Check if nvm is installed
      stat:
        path: "{{ ansible_user_dir }}/.nvm"
      register: nvm_stat
      become: no

    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        creates: "{{ ansible_user_dir }}/.nvm"
      when: not nvm_stat.stat.exists
      become: no
      tags:
        - nvm



    - name: Check if opencode is installed
      stat:
        path: "{{ ansible_user_dir }}/.opencode/bin/opencode"
      register: opencode_stat
      become: no

    - name: Install opencode
      ansible.builtin.shell: >
        curl -fsSL https://opencode.ai/install | bash
      args:
        creates: "{{ ansible_user_dir }}/.opencode/bin/opencode"
      when: not opencode_stat.stat.exists
      become: no
      tags:
        - opencode



    - name: Install getnf Nerd Font installer
      become: no
      ansible.builtin.shell: >
        curl -fsSL https://raw.githubusercontent.com/MounirErhili/getnf/main/install.sh | bash
      args:
        creates: "{{ ansible_user_dir }}/.local/bin/getnf"
      tags:
        - fonts



    - name: Update font cache
      become: no
      ansible.builtin.command: fc-cache -fv
      tags:
        - fonts

    - name: Set Zsh as default shell
      become: yes
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
      tags:
        - zsh

    - name: Install stow for dotfiles management
      become: yes
      dnf:
        name: stow
        state: present
      tags:
        - dotfiles
        - stow

    - name: Remove existing symlinks to avoid conflicts (restow)
      become: no
      ansible.builtin.command: stow -D .
      args:
        chdir: "{{ ansible_user_dir }}/.dotfiles"
      ignore_errors: yes
      tags:
        - dotfiles
        - stow

    - name: Stow dotfiles
      become: no
      ansible.builtin.command: stow .
      args:
        chdir: "{{ ansible_user_dir }}/.dotfiles"
      tags:
        - dotfiles
        - stow
