---
- name: Setup Hyprland Desktop Environment
  hosts: localhost
  connection: local
  become: yes

  vars:
    packages_to_install:
      - hyprland
      - kitty
      - hypridle
      - waybar
      - swww
      - swaync # Assuming this is a package name
      - pipewire-utils # Provides pactl and wpctl
      - brightnessctl
      - playerctl
      - grim # Screenshot utility, often used by hyprshot
      - slurp # Region selection utility, often used by hyprshot
      - hyprshot
      - hyprlock
      - wlogout
      - thunar
      - wofi
      # Add any other packages from .misc/fedora_setup/vars/packages.yml that are not already installed
      - git
      - neovim
      - jq
      - gcc
      - make
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - ncurses-devel
      - patch
      - unzip
      - curl
      - wget
      - zsh
      - python3-pip
      - tmux
      - htop
      - fastfetch

  tasks:
    - name: Install DNF packages
      ansible.builtin.dnf:
        name: "{{ packages_to_install }}"
        state: present
        update_cache: yes

    - name: Download Hack Nerd Font
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip
        dest: /tmp/Hack.zip

    - name: Unzip Hack Nerd Font
      ansible.builtin.unarchive:
        src: /tmp/Hack.zip
        dest: /usr/share/fonts
        remote_src: yes

    - name: Update font cache
      ansible.builtin.command: fc-cache -fv

    - name: Verify Hack Nerd Font is installed
      ansible.builtin.shell: fc-list | grep -i "hack nerd"
      register: font_check
      failed_when: font_check.rc != 0
