---
- name: Setup Arch Linux Development Environment
  hosts: localhost
  connection: local

  vars_files:
    - vars/packages.yml

  tasks:
    - name: Update all system packages
      become: yes
      ansible.builtin.pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - system

    - name: Install git early (required for ansible.builtin.git module)
      become: yes
      ansible.builtin.pacman:
        name: git
        state: present
      tags:
        - git

    - name: Install development packages
      become: yes
      ansible.builtin.pacman:
        name: "{{ packages }}"
        state: present
      tags:
        - packages

    - name: Install AUR helper (yay) dependencies
      become: yes
      ansible.builtin.pacman:
        name:
          - base-devel
          - git
        state: present
      tags:
        - aur

    - name: Check if yay is installed
      ansible.builtin.command: which yay
      register: yay_check
      ignore_errors: true
      changed_when: false

    - name: Remove existing yay build directory
      ansible.builtin.file:
        path: /tmp/yay
        state: absent
      when: yay_check.rc != 0

    - name: Clone yay repository
      ansible.builtin.git:
        repo: 'https://aur.archlinux.org/yay.git'
        dest: /tmp/yay
        force: yes
      when: yay_check.rc != 0
      become: no
      ignore_errors: true
      register: yay_clone

    - name: Build and install yay
      ansible.builtin.shell: |
        cd /tmp/yay
        makepkg -si --noconfirm
      when: yay_check.rc != 0 and yay_clone.rc == 0
      become: no
      ignore_errors: true
      register: yay_build

    - name: Warn if yay installation failed
      ansible.builtin.debug:
        msg: "WARNING: yay installation failed. Some AUR packages may not be available. Continuing with pacman packages only."
      when: yay_clone.rc != 0 or yay_build.rc != 0

    - name: Clean up yay build directory
      ansible.builtin.file:
        path: /tmp/yay
        state: absent
      when: yay_check.rc != 0

    - name: Install lazygit via AUR (if yay is available)
      ansible.builtin.shell: yay -S --noconfirm lazygit
      become: no
      when: yay_check.rc == 0
      ignore_errors: true
      tags:
        - lazygit

    - name: Install Yazi and recommended dependencies
      become: yes
      ansible.builtin.pacman:
        name:
          - yazi
          - p7zip
          - jq
          - poppler
          - fd
          - ripgrep
          - fzf
          - zoxide
          - imagemagick
          - xclip
        state: present
      tags:
        - yazi
      ignore_errors: true

    - name: Check if pyenv is installed
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.pyenv"
      register: pyenv_stat
      become: no

    - name: Install pyenv
      ansible.builtin.git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest: "{{ ansible_user_dir }}/.pyenv"
      when: not pyenv_stat.stat.exists
      become: no
      ignore_errors: true
      tags:
        - pyenv

    - name: Check if nvm is installed
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.nvm"
      register: nvm_stat
      become: no

    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        creates: "{{ ansible_user_dir }}/.nvm"
      when: not nvm_stat.stat.exists
      become: no
      ignore_errors: true
      tags:
        - nvm

    - name: Check if opencode is installed
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.opencode/bin/opencode"
      register: opencode_stat
      become: no

    - name: Install opencode
      ansible.builtin.shell: >
        curl -fsSL https://opencode.ai/install | bash
      args:
        creates: "{{ ansible_user_dir }}/.opencode/bin/opencode"
      when: not opencode_stat.stat.exists
      become: no
      ignore_errors: true
      tags:
        - opencode

    - name: Install getnf Nerd Font installer
      become: no
      ansible.builtin.shell: >
        curl -fsSL https://raw.githubusercontent.com/MounirErhili/getnf/main/install.sh | bash
      args:
        creates: "{{ ansible_user_dir }}/.local/bin/getnf"
      ignore_errors: true
      tags:
        - fonts

    - name: Update font cache
      become: no
      ansible.builtin.command: fc-cache -fv
      ignore_errors: true
      tags:
        - fonts

    - name: Set Zsh as default shell
      become: yes
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
      tags:
        - zsh
