---
- name: Setup Hyprland Desktop Environment on Arch Linux
  hosts: localhost
  connection: local
  become: yes

  vars:
    packages_to_install:
      - hyprland
      - kitty
      - hypridle
      - waybar
      - swww
      - swaync
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack
      - wireplumber
      - brightnessctl
      - playerctl
      - grim
      - slurp
      - hyprshot
      - hyprlock
      - wlogout
      - thunar
       - wofi
       - blueman
       - git
      - neovim
      - jq
      - gcc
      - make
      - zlib
      - bzip2
      - readline
      - sqlite
      - openssl
      - tk
      - libffi
      - xz
      - ncurses
      - patch
      - unzip
      - curl
      - wget
      - zsh
      - python-pip
      - tmux
      - htop
      - fastfetch

  tasks:
    - name: Update all system packages
      ansible.builtin.pacman:
        update_cache: yes
        upgrade: yes

    # NVIDIA Driver Detection and Installation
    - name: Check for NVIDIA GPU
      ansible.builtin.shell: lspci | grep -i nvidia
      register: nvidia_check
      ignore_errors: true
      changed_when: false

    - name: Display NVIDIA GPU detection result
      ansible.builtin.debug:
        msg: "NVIDIA GPU detected: {{ nvidia_check.stdout }}"
      when: nvidia_check.rc == 0

    - name: Prompt for NVIDIA driver installation
      ansible.builtin.pause:
        prompt: |
          NVIDIA GPU detected. Choose driver option:
          1. nvidia (latest drivers for modern GPUs - GTX 10 series and newer)
          2. nvidia-lts (stable drivers for LTS kernel)
          3. nvidia-dkms (DKMS drivers for custom kernels)
          4. nvidia-open (open source kernel modules - RTX 20 series and newer)
          5. skip (no NVIDIA drivers)
          Enter choice [1-5]
      register: nvidia_choice
      when: nvidia_check.rc == 0

    - name: Install NVIDIA drivers - latest
      ansible.builtin.pacman:
        name:
          - nvidia
          - nvidia-utils
          - nvidia-settings
        state: present
      when: nvidia_check.rc == 0 and nvidia_choice.user_input == "1"

    - name: Install NVIDIA drivers - LTS
      ansible.builtin.pacman:
        name:
          - nvidia-lts
          - nvidia-utils
          - nvidia-settings
        state: present
      when: nvidia_check.rc == 0 and nvidia_choice.user_input == "2"

    - name: Install NVIDIA drivers - DKMS
      ansible.builtin.pacman:
        name:
          - nvidia-dkms
          - nvidia-utils
          - nvidia-settings
        state: present
      when: nvidia_check.rc == 0 and nvidia_choice.user_input == "3"

    - name: Install NVIDIA drivers - Open source
      ansible.builtin.pacman:
        name:
          - nvidia-open
          - nvidia-utils
          - nvidia-settings
        state: present
      when: nvidia_check.rc == 0 and nvidia_choice.user_input == "4"

    - name: Configure NVIDIA for Hyprland
      ansible.builtin.blockinfile:
        path: /etc/modprobe.d/nvidia.conf
        create: yes
        block: |
          # Enable NVIDIA DRM kernel mode setting
          options nvidia_drm modeset=1
          options nvidia_drm fbdev=1
        marker: "# {mark} ANSIBLE MANAGED BLOCK - NVIDIA"
      when: nvidia_check.rc == 0 and nvidia_choice.user_input in ["1", "2", "3", "4"]

    - name: Add NVIDIA modules to mkinitcpio
      ansible.builtin.lineinfile:
        path: /etc/mkinitcpio.conf
        regexp: '^MODULES='
        line: 'MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)'
        backup: yes
      when: nvidia_check.rc == 0 and nvidia_choice.user_input in ["1", "2", "3", "4"]
      notify: regenerate_initramfs

    - name: Set NVIDIA environment variables for Hyprland
      ansible.builtin.blockinfile:
        path: /etc/environment
        create: yes
        block: |
          # NVIDIA environment variables for Hyprland
          LIBVA_DRIVER_NAME=nvidia
          XDG_SESSION_TYPE=wayland
          GBM_BACKEND=nvidia-drm
          __GLX_VENDOR_LIBRARY_NAME=nvidia
          WLR_NO_HARDWARE_CURSORS=1
        marker: "# {mark} ANSIBLE MANAGED BLOCK - NVIDIA HYPRLAND"
      when: nvidia_check.rc == 0 and nvidia_choice.user_input in ["1", "2", "3", "4"]

    - name: Install base packages
      ansible.builtin.pacman:
        name: "{{ packages_to_install }}"
        state: present
        update_cache: yes

    - name: Install flatpak
      ansible.builtin.pacman:
        name: flatpak
        state: present

    - name: Add flathub repository
      ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      args:
        creates: /var/lib/flatpak/repo/flathub.flatpakrepo

    - name: Install Obsidian via flatpak
      ansible.builtin.command: flatpak install -y flathub md.obsidian.Obsidian
      become: no

    - name: Ensure pipewire is enabled and running
      ansible.builtin.systemd_user:
        name: pipewire
        enabled: yes
        state: started
      become: no

    - name: Ensure wireplumber is enabled and running
      ansible.builtin.systemd_user:
        name: wireplumber
        enabled: yes
        state: started
      become: no

    - name: Install pulsemixer
      become: no
      ansible.builtin.pip:
        name: pulsemixer
        state: present
        executable: pip

    - name: Check if Hack Nerd Font is already installed
      ansible.builtin.shell: fc-list | grep -i "hack nerd"
      register: font_check
      ignore_errors: true
      changed_when: false

    - name: Download Hack Nerd Font
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip
        dest: /tmp/Hack.zip
        timeout: 30
        retries: 3
        delay: 10
      when: font_check.rc != 0

    - name: Unzip Hack Nerd Font
      ansible.builtin.unarchive:
        src: /tmp/Hack.zip
        dest: /usr/share/fonts
        remote_src: yes
      when: font_check.rc != 0

    - name: Update font cache
      ansible.builtin.command: fc-cache -fv
      when: font_check.rc != 0

    - name: Verify Hack Nerd Font is installed
      ansible.builtin.shell: fc-list | grep -i "hack nerd"
      register: final_font_check
      failed_when: final_font_check.rc != 0

  handlers:
    - name: regenerate_initramfs
      ansible.builtin.command: mkinitcpio -P
      listen: regenerate_initramfs
