---
- name: Setup Arch Linux Development Environment
  hosts: localhost
  connection: local

  vars_files:
    - vars/packages.yml

  tasks:
    - name: Update all system packages
      become: yes
      ansible.builtin.pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - system

    - name: Install git early (required for ansible.builtin.git module)
      become: yes
      ansible.builtin.pacman:
        name: git
        state: present
      tags:
        - git

    - name: Install development packages
      become: yes
      ansible.builtin.pacman:
        name: "{{ packages }}"
        state: present
      tags:
        - packages

    - name: Install AUR helper (yay) dependencies
      become: yes
      ansible.builtin.pacman:
        name:
          - base-devel
          - git
        state: present
      tags:
        - aur

    - name: Check if yay is installed
      ansible.builtin.command: which yay
      register: yay_check
      ignore_errors: true
      changed_when: false
      tags:
        - aur

    - name: Display yay already installed
      ansible.builtin.debug:
        msg: "yay is already installed at {{ yay_check.stdout }}"
      when: yay_check.rc == 0
      tags:
        - aur

    - name: Run yay installer script (if not installed)
      ansible.builtin.shell: bash "{{ playbook_dir }}/install_yay.sh"
      when: yay_check.rc != 0
      become: no
      ignore_errors: true
      register: yay_install_result
      tags:
        - aur

    - name: Re-check yay installation after script
      ansible.builtin.command: which yay
      register: yay_final_check
      ignore_errors: true
      changed_when: false
      tags:
        - aur

    - name: Display final yay status
      ansible.builtin.debug:
        msg: "yay installation successful: {{ yay_final_check.stdout }}"
      when: yay_final_check.rc == 0
      tags:
        - aur

    - name: Display yay installation failed warning
      ansible.builtin.debug:
        msg: "WARNING: yay installation failed. Continuing with pacman packages only."
      when: yay_final_check.rc != 0
      tags:
        - aur

    - name: Install lazygit via AUR (if yay is available)
      ansible.builtin.shell: yay -S --noconfirm lazygit
      become: no
      when: yay_final_check.rc == 0
      ignore_errors: true
      tags:
        - lazygit

    - name: Install Yazi and recommended dependencies
      become: yes
      ansible.builtin.pacman:
        name:
          - yazi
          - p7zip
          - jq
          - poppler
          - fd
          - ripgrep
          - fzf
          - zoxide
          - imagemagick
          - xclip
        state: present
      tags:
        - yazi
      ignore_errors: true

    - name: Check if pyenv is installed
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.pyenv"
      register: pyenv_stat
      become: no

    - name: Install pyenv
      ansible.builtin.git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest: "{{ ansible_user_dir }}/.pyenv"
      when: not pyenv_stat.stat.exists
      become: no
      ignore_errors: true
      tags:
        - pyenv

    - name: Check if nvm is installed
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.nvm"
      register: nvm_stat
      become: no

    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        creates: "{{ ansible_user_dir }}/.nvm"
      when: not nvm_stat.stat.exists
      become: no
      ignore_errors: true
      tags:
        - nvm

    - name: Check if opencode is installed
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/.opencode/bin/opencode"
      register: opencode_stat
      become: no

    - name: Install opencode
      ansible.builtin.shell: >
        curl -fsSL https://opencode.ai/install | bash
      args:
        creates: "{{ ansible_user_dir }}/.opencode/bin/opencode"
      when: not opencode_stat.stat.exists
      become: no
      ignore_errors: true
      tags:
        - opencode

    - name: Install getnf Nerd Font installer
      become: no
      ansible.builtin.shell: >
        curl -fsSL https://raw.githubusercontent.com/MounirErhili/getnf/main/install.sh | bash
      args:
        creates: "{{ ansible_user_dir }}/.local/bin/getnf"
      ignore_errors: true
      tags:
        - fonts

    - name: Update font cache
      become: no
      ansible.builtin.command: fc-cache -fv
      ignore_errors: true
      tags:
        - fonts

    - name: Set Zsh as default shell
      become: yes
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
      tags:
        - zsh
