#!/bin/bash

# Generate GTK3/GTK4 CSS from pywal colors
# This applies pywal colors to GTK apps using custom CSS

source ~/.cache/wal/colors.sh

# Create GTK3 config dir if needed
mkdir -p ~/.config/gtk-3.0
mkdir -p ~/.config/gtk-4.0

# Generate GTK3 CSS
cat > ~/.config/gtk-3.0/gtk.css << EOF
/* Generated by pywal-gtk.sh */
@define-color accent_color ${color4};
@define-color accent_bg_color ${color4};
@define-color accent_fg_color ${foreground};
@define-color window_bg_color ${background};
@define-color window_fg_color ${foreground};
@define-color view_bg_color ${background};
@define-color view_fg_color ${foreground};
@define-color headerbar_bg_color ${color0};
@define-color headerbar_fg_color ${foreground};
@define-color card_bg_color ${color0};
@define-color card_fg_color ${foreground};
@define-color popover_bg_color ${color0};
@define-color popover_fg_color ${foreground};
@define-color shade_color rgba(0,0,0,0.36);
@define-color scrollbar_outline_color rgba(0,0,0,0.5);

/* Additional styling */
window, .background {
    background-color: @window_bg_color;
    color: @window_fg_color;
}

headerbar, .titlebar, .titlebar .background,
headerbar.default-decoration,
window.background headerbar,
window headerbar.titlebar {
    background-color: @headerbar_bg_color;
    background-image: none;
    color: @headerbar_fg_color;
    border: none;
    box-shadow: none;
}

headerbar button, .titlebar button {
    background-color: transparent;
    background-image: none;
    color: @headerbar_fg_color;
}

headerbar entry {
    background-color: shade(@headerbar_bg_color, 1.1);
    color: @headerbar_fg_color;
}

.sidebar, placessidebar {
    background-color: shade(@window_bg_color, 0.95);
}

button:hover {
    background-color: alpha(@accent_color, 0.1);
}

button:active, button:checked {
    background-color: @accent_color;
    color: @accent_fg_color;
}

selection, *:selected {
    background-color: alpha(@accent_color, 0.3);
}

entry, textview, .view {
    background-color: @view_bg_color;
    color: @view_fg_color;
}

.navigation-sidebar row:selected {
    background-color: alpha(@accent_color, 0.15);
}
EOF

# Generate GTK4 CSS (libadwaita)
cat > ~/.config/gtk-4.0/gtk.css << EOF
/* Generated by pywal-gtk.sh */
@define-color accent_color ${color4};
@define-color accent_bg_color ${color4};
@define-color accent_fg_color ${foreground};
@define-color window_bg_color ${background};
@define-color window_fg_color ${foreground};
@define-color view_bg_color ${background};
@define-color view_fg_color ${foreground};
@define-color headerbar_bg_color ${color0};
@define-color headerbar_fg_color ${foreground};
@define-color card_bg_color ${color0};
@define-color card_fg_color ${foreground};
@define-color popover_bg_color ${color0};
@define-color popover_fg_color ${foreground};
@define-color shade_color rgba(0,0,0,0.36);
@define-color scrollbar_outline_color rgba(0,0,0,0.5);
EOF

# Update settings.ini files
cat > ~/.config/gtk-3.0/settings.ini << EOF
[Settings]
gtk-application-prefer-dark-theme=1
gtk-theme-name=Adwaita-dark
EOF

cat > ~/.config/gtk-4.0/settings.ini << EOF
[Settings]
gtk-application-prefer-dark-theme=1
gtk-theme-name=Adwaita-dark
EOF

# Set gsettings for portal/dconf-aware apps
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null

echo "GTK theme updated from pywal colors"
