---
- name: Setup Ubuntu 22.04 Development Environment
  hosts: localhost
  connection: local

  vars_files:
    - vars/packages.yml

  tasks:
    - name: Update all system packages
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags:
        - system

    - name: Install development packages
      become: yes
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      tags:
        - packages

    # Docker installation - using official Docker repository for Ubuntu 22.04
    - name: Install required packages for Docker
      become: yes
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Add Docker GPG key
      become: yes
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.asc
        mode: '0644'
      tags:
        - docker

    - name: Add Docker APT repository
      become: yes
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: yes
      tags:
        - docker

    - name: Install Docker packages
      become: yes
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Start and enable Docker service
      become: yes
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
      tags:
        - docker

    - name: Add current user to docker group
      become: yes
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
      tags:
        - docker

    # Lazygit installation - using GitHub releases for Ubuntu 22.04
    - name: Check if lazygit is already installed
      ansible.builtin.command: which lazygit
      register: lazygit_check
      ignore_errors: yes
      changed_when: false
      tags:
        - lazygit

    - name: Get latest lazygit release info
      ansible.builtin.uri:
        url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
        method: GET
        return_content: yes
      register: lazygit_release
      when: lazygit_check.rc != 0
      tags:
        - lazygit

    - name: Download and install lazygit
      become: yes
      ansible.builtin.unarchive:
        src: "{{ lazygit_release.json.assets | selectattr('name', 'search', 'Linux_x86_64.tar.gz') | list | first | json_query('browser_download_url') }}"
        dest: /usr/local/bin
        remote_src: yes
        creates: /usr/local/bin/lazygit
        owner: root
        group: root
        mode: '0755'
      when: lazygit_check.rc != 0
      tags:
        - lazygit

    # Yazi installation - improved approach for Ubuntu 22.04
    - name: Check if yazi is already installed
      ansible.builtin.command: which yazi
      register: yazi_check
      ignore_errors: yes
      changed_when: false
      tags:
        - yazi

    - name: Install Rustup (for Yazi)
      ansible.builtin.shell: >
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "{{ ansible_user_dir }}/.cargo/bin/cargo"
      when: yazi_check.rc != 0
      become: no
      tags:
        - yazi

    - name: Install Yazi via cargo
      ansible.builtin.shell: >
        source {{ ansible_user_dir }}/.cargo/env && cargo install --locked yazi-fm yazi-cli
      args:
        creates: "{{ ansible_user_dir }}/.cargo/bin/yazi"
      when: yazi_check.rc != 0
      become: no
      tags:
        - yazi

    - name: Create symlink for yazi in /usr/local/bin
      become: yes
      ansible.builtin.file:
        src: "{{ ansible_user_dir }}/.cargo/bin/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        state: link
      loop:
        - yazi
        - ya
      when: yazi_check.rc != 0
      tags:
        - yazi

    - name: Install Yazi recommended dependencies
      become: yes
      ansible.builtin.apt:
        name:
          - ffmpeg
          - p7zip-full
          - jq
          - poppler-utils
          - fd-find
          - ripgrep
          - fzf
          - zoxide
          - imagemagick
          - xclip
        state: present
      tags:
        - yazi

    # Pyenv installation
    - name: Check if pyenv is installed
      stat:
        path: "{{ ansible_user_dir }}/.pyenv"
      register: pyenv_stat
      become: no

    - name: Install pyenv dependencies
      become: yes
      ansible.builtin.apt:
        name:
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - libssl-dev
          - libffi-dev
          - liblzma-dev
          - python3-dev
        state: present
      when: not pyenv_stat.stat.exists
      tags:
        - pyenv

    - name: Install pyenv
      ansible.builtin.git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest: "{{ ansible_user_dir }}/.pyenv"
      when: not pyenv_stat.stat.exists
      become: no
      tags:
        - pyenv

    # NVM installation
    - name: Check if nvm is installed
      stat:
        path: "{{ ansible_user_dir }}/.nvm"
      register: nvm_stat
      become: no

    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        creates: "{{ ansible_user_dir }}/.nvm"
      when: not nvm_stat.stat.exists
      become: no
      tags:
        - nvm

    # OpenCode installation
    - name: Check if opencode is installed
      stat:
        path: "{{ ansible_user_dir }}/.opencode/bin/opencode"
      register: opencode_stat
      become: no

    - name: Install opencode
      ansible.builtin.shell: >
        curl -fsSL https://opencode.ai/install | bash
      args:
        creates: "{{ ansible_user_dir }}/.opencode/bin/opencode"
      when: not opencode_stat.stat.exists
      become: no
      tags:
        - opencode

    # Font installation
    - name: Install getnf Nerd Font installer
      become: no
      ansible.builtin.shell: >
        curl -fsSL https://raw.githubusercontent.com/MounirErhili/getnf/main/install.sh | bash
      args:
        creates: "{{ ansible_user_dir }}/.local/bin/getnf"
      tags:
        - fonts

    - name: Update font cache
      become: no
      ansible.builtin.command: fc-cache -fv
      tags:
        - fonts

    # Shell configuration
    - name: Set Zsh as default shell
      become: yes
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
      tags:
        - zsh

    # Additional Ubuntu 22.04 specific configurations
    - name: Install snap packages
      become: yes
      ansible.builtin.snap:
        name: "{{ item }}"
        state: present
      loop:
        - code
        - discord
      ignore_errors: yes
      tags:
        - snap
        - optional

    - name: Enable firewall (ufw)
      become: yes
      ansible.builtin.ufw:
        state: enabled
        policy: deny
        direction: incoming
      tags:
        - security
        - firewall

    - name: Allow SSH through firewall
      become: yes
      ansible.builtin.ufw:
        rule: allow
        name: OpenSSH
      tags:
        - security
        - firewall