---
- name: Setup Arch Linux Development Environment
  hosts: localhost
  connection: local

  vars_files:
    - vars/packages.yml
  
  vars:
    aur_builder_user: aur_builder
    yay_build_dir: "/tmp/yay-{{ ansible_date_time.epoch }}"
    max_retries: 3
    retry_delay: 10

  tasks:
    - name: Update all system packages
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - system

    - name: Install git early (required for ansible.builtin.git module)
      become: yes
      pacman:
        name: git
        state: present
      tags:
        - git

    - name: Install development packages
      become: yes
      pacman:
        name: "{{ packages }}"
        state: present
      tags:
        - packages

    # === ROBUST YAY INSTALLATION ===
    
    - name: Install AUR helper (yay) dependencies
      become: yes
      pacman:
        name:
          - base-devel
          - git
        state: present
        update_cache: yes
      retries: "{{ max_retries }}"
      delay: "{{ retry_delay }}"
      tags:
        - aur

    - name: Create dedicated AUR builder user
      become: yes
      user:
        name: "{{ aur_builder_user }}"
        create_home: yes
        group: wheel
        shell: /bin/bash
        state: present
      tags:
        - aur

    - name: Configure sudo for AUR builder (pacman only)
      become: yes
      lineinfile:
        path: "/etc/sudoers.d/11-install-{{ aur_builder_user }}"
        line: "{{ aur_builder_user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        mode: '0644'
        validate: 'visudo -cf %s'
      tags:
        - aur

    - name: Check if yay is already installed
      stat:
        path: /usr/bin/yay
      register: yay_check
      become: no

    - name: Verify network connectivity to AUR
      uri:
        url: https://aur.archlinux.org
        method: GET
        timeout: 30
      register: aur_connectivity
      retries: "{{ max_retries }}"
      delay: "{{ retry_delay }}"
      when: not yay_check.stat.exists

    - name: Remove existing build directory
      file:
        path: "{{ yay_build_dir }}"
        state: absent
      when: not yay_check.stat.exists
      become: no

    - name: Clone yay repository with validation
      git:
        repo: 'https://aur.archlinux.org/yay.git'
        dest: "{{ yay_build_dir }}"
        force: yes
        verify_commit: no
      become: no
      become_user: "{{ aur_builder_user }}"
      when: not yay_check.stat.exists
      retries: "{{ max_retries }}"
      delay: "{{ retry_delay }}"
      tags:
        - aur

    - name: Verify repository integrity
      stat:
        path: "{{ yay_build_dir }}/PKGBUILD"
      register: pkgbuild_exists
      when: not yay_check.stat.exists

    - name: Fail if PKGBUILD missing
      fail:
        msg: "PKGBUILD not found in cloned repository"
      when: not yay_check.stat.exists and not pkgbuild_exists.stat.exists

    - name: Set proper ownership of build directory
      file:
        path: "{{ yay_build_dir }}"
        owner: "{{ aur_builder_user }}"
        group: "{{ aur_builder_user }}"
        recurse: yes
      become: yes
      when: not yay_check.stat.exists

    - name: Build yay package with comprehensive error handling
      shell: |
        cd {{ yay_build_dir }}
        # Clean any previous build artifacts
        rm -f *.pkg.tar.zst *.pkg.tar.xz
        # Build with verbose output and proper flags
        makepkg -sf --noconfirm --needed --noprogressbar
      become: no
      become_user: "{{ aur_builder_user }}"
      when: not yay_check.stat.exists
      register: build_result
      retries: "{{ max_retries }}"
      delay: "{{ retry_delay }}"
      until: build_result is succeeded
      tags:
        - aur

    - name: Find built yay package
      find:
        paths: "{{ yay_build_dir }}"
        patterns: 
          - "yay-*.pkg.tar.zst"
          - "yay-*.pkg.tar.xz"
      register: yay_packages
      when: not yay_check.stat.exists and build_result is succeeded

    - name: Fail if no package built
      fail:
        msg: "No yay package found after build"
      when: not yay_check.stat.exists and yay_packages.files|length == 0

    - name: Install yay package using pacman -U
      command: "pacman -U --noconfirm {{ yay_packages.files[0].path }}"
      become: yes
      when: not yay_check.stat.exists and yay_packages.files|length > 0
      tags:
        - aur

    - name: Clean up build directory
      file:
        path: "{{ yay_build_dir }}"
        state: absent
      when: not yay_check.stat.exists
      become: no

    - name: Verify yay installation
      command: yay --version
      register: yay_version_check
      become: no
      changed_when: false
      failed_when: yay_version_check.rc != 0

    - name: Display yay installation result
      debug:
        msg: "YAY installed successfully. Version: {{ yay_version_check.stdout }}"

    - name: Test yay functionality
      command: yay -Ps
      register: yay_test
      become: no
      become_user: "{{ aur_builder_user }}"
      changed_when: false

    # === AUR PACKAGE INSTALLATIONS ===

    - name: Install lazygit via AUR
      shell: yay -S --noconfirm lazygit
      become: no
      become_user: "{{ aur_builder_user }}"
      retries: "{{ max_retries }}"
      delay: "{{ retry_delay }}"
      tags:
        - lazygit

    - name: Install Yazi and recommended dependencies
      become: yes
      ansible.builtin.pacman:
        name:
          - yazi
          - p7zip # 7zip
          - jq
          - poppler
          - fd # fd
          - ripgrep
          - fzf
          - zoxide
          - imagemagick
          - xclip # for clipboard support
        state: present
      tags:
        - yazi

    - name: Check if pyenv is installed
      stat:
        path: "{{ ansible_user_dir }}/.pyenv"
      register: pyenv_stat
      become: no

    - name: Install pyenv
      ansible.builtin.git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest: "{{ ansible_user_dir }}/.pyenv"
      when: not pyenv_stat.stat.exists
      become: no
      tags:
        - pyenv

    - name: Check if nvm is installed
      stat:
        path: "{{ ansible_user_dir }}/.nvm"
      register: nvm_stat
      become: no

    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        creates: "{{ ansible_user_dir }}/.nvm"
      when: not nvm_stat.stat.exists
      become: no
      tags:
        - nvm

    - name: Check if opencode is installed
      stat:
        path: "{{ ansible_user_dir }}/.opencode/bin/opencode"
      register: opencode_stat
      become: no

    - name: Install opencode
      ansible.builtin.shell: >
        curl -fsSL https://opencode.ai/install | bash
      args:
        creates: "{{ ansible_user_dir }}/.opencode/bin/opencode"
      when: not opencode_stat.stat.exists
      become: no
      tags:
        - opencode

    - name: Install getnf Nerd Font installer
      become: no
      ansible.builtin.shell: >
        curl -fsSL https://raw.githubusercontent.com/MounirErhili/getnf/main/install.sh | bash
      args:
        creates: "{{ ansible_user_dir }}/.local/bin/getnf"
      tags:
        - fonts

    - name: Update font cache
      become: no
      ansible.builtin.command: fc-cache -fv
      tags:
        - fonts

    - name: Set Zsh as default shell
      become: yes
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
      tags:
        - zsh
