---
- name: Setup Hyprland Desktop Environment
  hosts: localhost
  connection: local
  become: yes

  vars:
    packages_to_install:
      - hyprland
      - kitty
      - hypridle
      - waybar
      - swww
      - swaync
      - pipewire-utils
      - brightnessctl
      - playerctl
      - grim
      - slurp
      - hyprshot
      - hyprlock
      - wlogout
      - thunar
      - wofi
      - git
      - neovim
      - jq
      - gcc
      - make
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - ncurses-devel
      - patch
      - unzip
      - curl
      - wget
      - zsh
      - python3-pip
      - tmux
      - htop
      - fastfetch
      - stow
      - gamescope
      - steam
      - gamemode


  tasks:
    - name: Enable RPMFusion free repository
      ansible.builtin.command: dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      args:
        creates: /etc/yum.repos.d/rpmfusion-free.repo

    - name: Enable RPMFusion non-free repository
      ansible.builtin.command: dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      args:
        creates: /etc/yum.repos.d/rpmfusion-nonfree.repo

    - name: Install DNF packages
      ansible.builtin.dnf:
        name: "{{ packages_to_install }}"
        state: present
        update_cache: yes

    - name: Install flatpak
      ansible.builtin.dnf:
        name: flatpak
        state: present

    - name: Add flathub repository
      ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      args:
        creates: /var/lib/flatpak/repo/flathub.flatpakrepo

    - name: Install Obsidian via flatpak
      ansible.builtin.command: flatpak install -y flathub md.obsidian.Obsidian

    - name: Install Zen via flatpak
      ansible.builtin.command: flatpak install -y flathub app.zen_browser.zen

    - name: Install pulsemixer
      become: no
      ansible.builtin.pip:
        name: pulsemixer
        state: present
        executable: pip3

    - name: Check if Hack Nerd Font is already installed
      ansible.builtin.shell: fc-list | grep -i "hack nerd"
      register: font_check
      ignore_errors: true

    - name: Download Hack Nerd Font
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip
        dest: /tmp/Hack.zip
        timeout: 30
        retries: 3
        delay: 10
      when: font_check.rc != 0

    - name: Unzip Hack Nerd Font
      ansible.builtin.unarchive:
        src: /tmp/Hack.zip
        dest: /usr/share/fonts
        remote_src: yes
      when: font_check.rc != 0

    - name: Update font cache
      ansible.builtin.command: fc-cache -fv
      when: font_check.rc != 0

    - name: Verify Hack Nerd Font is installed
      ansible.builtin.shell: fc-list | grep -i "hack nerd"
      register: final_font_check
      failed_when: final_font_check.rc != 0

    - name: Enable Steam Play for all titles (Proton)
      become: no
      ansible.builtin.lineinfile:
        path: ~/.steam/steam/config/config.vdf
        line: '			"ToolMapping"		"proton_*"'
        create: yes
      ignore_errors: true

    - name: Create gamescope desktop entry for Steam Big Picture
      ansible.builtin.copy:
        dest: /usr/share/applications/steam-bigpicture-gamescope.desktop
        content: |
          [Desktop Entry]
          Name=Steam Big Picture (Gamescope)
          Comment=Launch Steam Big Picture mode with gamescope for optimal performance
          Exec=gamescope -W 1920 -H 1080 -r 60 -- steam -gamepadui
          Icon=steam
          Terminal=false
          Type=Application
          Categories=Game;
        mode: '0644'

    - name: Install gaming helper script
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/gaming-helper.sh"
        dest: /usr/local/bin/gaming-helper
        mode: '0755'

    - name: Check if dotfiles directory exists
      become: no
      ansible.builtin.stat:
        path: ~/.dotfiles
      register: dotfiles_check

    - name: Clone dotfiles repository
      become: no
      ansible.builtin.git:
        repo: https://github.com/YOUR_USERNAME/dotfiles.git
        dest: ~/.dotfiles
        clone: yes
      when: not dotfiles_check.stat.exists
      # Note: Replace YOUR_USERNAME/dotfiles.git with your actual dotfiles repository URL
      # Or comment out this task if you're already in your dotfiles directory

    - name: Stow dotfiles configuration
      become: no
      ansible.builtin.shell: |
        cd ~/.dotfiles
        stow .
      args:
        creates: ~/.zshrc

    - name: Stow wallpapers
      become: no
      ansible.builtin.shell: |
        cd ~/.dotfiles
        stow wallpapers
      args:
        creates: ~/Wallpapers
